### PR TITLE
Don’t cache when resp.statusCode !== 200

### PR DESCRIPTION
**Pull request by kesla**

### CODE REVIEW

**Comment by mikeal** [comment]
Can we make this an option. It's pretty beneficial to cache 404 responses, especially for files that don't exist, it saves you a filesystem operation. Think about the case where you don't have a favico.ico, every browser client will ask for it at least once.

**Comment by kesla** [comment]
@mikeal Cool, that makes a lot of sense, added a flag (cacheErrors) to opts, and default to the current behaviour.

**Comment by mikeal** [comment]
the best default may be _not_ to cache them actually. it seems ituitive
that it wouldnt i just dont want to lose that caching when you do want to
cache errors.

**Comment by kesla** [comment]
@mikeal alright, done.

**Pull request merged**
